# Generated by Django 4.2.1 on 2023-06-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='content',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='AppTienda'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
