# Generated by Django 4.2.1 on 2023-06-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0003_producto_description_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default='AppTienda/assets/img/default.jpg', upload_to=''),
        ),
    ]
